// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Chatterino/api/internal/resolvers/imgur (interfaces: ImgurClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	imgur "github.com/koffeinsource/go-imgur"
)

// MockImgurClient is a mock of ImgurClient interface.
type MockImgurClient struct {
	ctrl     *gomock.Controller
	recorder *MockImgurClientMockRecorder
}

// MockImgurClientMockRecorder is the mock recorder for MockImgurClient.
type MockImgurClientMockRecorder struct {
	mock *MockImgurClient
}

// NewMockImgurClient creates a new mock instance.
func NewMockImgurClient(ctrl *gomock.Controller) *MockImgurClient {
	mock := &MockImgurClient{ctrl: ctrl}
	mock.recorder = &MockImgurClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImgurClient) EXPECT() *MockImgurClientMockRecorder {
	return m.recorder
}

// GetInfoFromURL mocks base method.
func (m *MockImgurClient) GetInfoFromURL(arg0 string) (*imgur.GenericInfo, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfoFromURL", arg0)
	ret0, _ := ret[0].(*imgur.GenericInfo)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetInfoFromURL indicates an expected call of GetInfoFromURL.
func (mr *MockImgurClientMockRecorder) GetInfoFromURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfoFromURL", reflect.TypeOf((*MockImgurClient)(nil).GetInfoFromURL), arg0)
}
