// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Chatterino/api/internal/resolvers/twitch (interfaces: TwitchAPIClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	helix "github.com/nicklaw5/helix"
)

// MockTwitchAPIClient is a mock of TwitchAPIClient interface.
type MockTwitchAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockTwitchAPIClientMockRecorder
}

// MockTwitchAPIClientMockRecorder is the mock recorder for MockTwitchAPIClient.
type MockTwitchAPIClientMockRecorder struct {
	mock *MockTwitchAPIClient
}

// NewMockTwitchAPIClient creates a new mock instance.
func NewMockTwitchAPIClient(ctrl *gomock.Controller) *MockTwitchAPIClient {
	mock := &MockTwitchAPIClient{ctrl: ctrl}
	mock.recorder = &MockTwitchAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTwitchAPIClient) EXPECT() *MockTwitchAPIClientMockRecorder {
	return m.recorder
}

// GetClips mocks base method.
func (m *MockTwitchAPIClient) GetClips(arg0 *helix.ClipsParams) (*helix.ClipsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClips", arg0)
	ret0, _ := ret[0].(*helix.ClipsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClips indicates an expected call of GetClips.
func (mr *MockTwitchAPIClientMockRecorder) GetClips(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClips", reflect.TypeOf((*MockTwitchAPIClient)(nil).GetClips), arg0)
}
