// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Chatterino/api/internal/resolvers/twitch (interfaces: TwitchAPIClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gotwitch "github.com/dankeroni/gotwitch"
	gomock "github.com/golang/mock/gomock"
)

// MockTwitchAPIClient is a mock of TwitchAPIClient interface.
type MockTwitchAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockTwitchAPIClientMockRecorder
}

// MockTwitchAPIClientMockRecorder is the mock recorder for MockTwitchAPIClient.
type MockTwitchAPIClientMockRecorder struct {
	mock *MockTwitchAPIClient
}

// NewMockTwitchAPIClient creates a new mock instance.
func NewMockTwitchAPIClient(ctrl *gomock.Controller) *MockTwitchAPIClient {
	mock := &MockTwitchAPIClient{ctrl: ctrl}
	mock.recorder = &MockTwitchAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTwitchAPIClient) EXPECT() *MockTwitchAPIClientMockRecorder {
	return m.recorder
}

// GetClip mocks base method.
func (m *MockTwitchAPIClient) GetClip(arg0 string) (gotwitch.V5GetClipResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClip", arg0)
	ret0, _ := ret[0].(gotwitch.V5GetClipResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetClip indicates an expected call of GetClip.
func (mr *MockTwitchAPIClientMockRecorder) GetClip(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClip", reflect.TypeOf((*MockTwitchAPIClient)(nil).GetClip), arg0)
}
