global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['pg_exporter:9187']

  - job_name: 'chatterino2_api'
    static_configs:
      - targets: ['api:9182']
