---
name: Build

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: ["oldstable", "stable"]
        os: ["ubuntu-24.04"]

    steps:
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Get external dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu-')
        run: sudo apt update && sudo apt -y install build-essential libvips-dev

      - name: Get Go dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -ldflags="-s -w" -v -o ../../build/chatterino-api
        working-directory: cmd/api

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: chatterino-api-${{ matrix.go }}-${{ matrix.os }}
          path: build/chatterino-api

  create-release:
    needs: build
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: "project-git-repo"
          persist-credentials: false

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: chatterino-api-stable-ubuntu-24.04
          path: bins/ubuntu/

      - name: display structure
        run: ls -lR

      - name: rename files
        run: |
          mkdir final-bins
          mv bins/ubuntu/chatterino-api final-bins/chatterino-api-ubuntu-x86_64

      - name: build-changelog
        run: sed "0,/## $(echo "$GITHUB_REF_VALUE" | cut -d '/' -f 3 | cut -c2-)/d" project-git-repo/CHANGELOG.md | sed '/^## /,+999999999999999999 d' | tail -n+2 | head -n-1 > release-body
        env:
          GITHUB_REF_VALUE: ${{ github.ref }}

      - name: create release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          body_path: release-body
          files: |
            final-bins/chatterino-api-ubuntu-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
