---
name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        go: ["1.19", "1.20"]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt -y install build-essential libvips-dev

      # This will install the staticcheck version as described in the go.mod file
      - name: Install linter
        run: go install honnef.co/go/tools/cmd/staticcheck

      - name: Lint
        run: staticcheck ./...
