---
name: Test

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

jobs:
  test:
    name: "Test & upload coverage (${{ matrix.go }})"
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        go: ["oldstable", "stable"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go }}

      - name: Get external dependencies (Ubuntu)
        run: sudo apt update && sudo apt -y install build-essential libvips-dev
      - name: Migration test
        run: go test -v -tags migrationtest ./...
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -tags test ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        if: matrix.go == 'stable'
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
